In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.2'

In [3]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
array2=np.array([[1,2],
                 [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [8]:
array3d=np.array(
                  [[
                      [1,2],
                      [3,4]],
                      [
                        [5,6],
                        [7,8]
                      ]
                  ]
)
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
array3d.shape

(2, 2, 2)

In [10]:
array3ex=np.array([[
    [1,2,3],
    [2,3,4],
    [3,4,5]],
    [[5,6,7],
    [6,7,8],
    [7,8,9]]]
)
array3ex

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]])

In [11]:
array3ex.shape

(2, 3, 3)

In [14]:
array4d=np.array([
    [[[1,2],
     [2,3],
     [3,4]],
     
    [[4,5],
    [5,6],
    [6,7]],
     
    [[7,8],
    [8,9],
    [9,10]]],
    [
     [[1,2],
     [2,3],
     [3,4]],
        
    [[4,5],
    [5,6],
    [6,7]],
        
    [[7,8],
    [8,9],
    [9,10]]
    ]
]
)
array4d

array([[[[ 1,  2],
         [ 2,  3],
         [ 3,  4]],

        [[ 4,  5],
         [ 5,  6],
         [ 6,  7]],

        [[ 7,  8],
         [ 8,  9],
         [ 9, 10]]],


       [[[ 1,  2],
         [ 2,  3],
         [ 3,  4]],

        [[ 4,  5],
         [ 5,  6],
         [ 6,  7]],

        [[ 7,  8],
         [ 8,  9],
         [ 9, 10]]]])