In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.2'

array1=np.array([1,2,3])

In [4]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [5]:
array2=np.array([[1,2],
               [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [6]:
array3d=np.array([[
                  [1,2],
                  [3,4]
                 ],
                 [
                 [5,6],
                 [7,8]
                 ]
                 ])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
array3d.shape


(2, 2, 2)

In [8]:
array3ex=np.array([
                  [
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ],
                  [
                   [10,11,12],
                   [13,14,15],
                   [16,17,18]   
                  ]
])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
array3ex.shape

(2, 3, 3)

In [10]:
array4d=np.array([
                 [
                  [
                   [1,2],
                   [3,4],
                   [5,6]   
                  ],
                    [
                     [7,8],
                     [9,10],
                     [11,12]   
                    ],
                     [
                      [13,14],
                      [15,16],
                      [17,18]   
                     ]   
                 ],
                 
                 [
                  [
                   [19,20],
                   [21,22],
                   [23,24]   
                  ],
                    [
                     [25,26],
                     [27,28],
                     [29,30]   
                    ],
                     [
                      [31,32],
                      [33,34],
                      [35,36]   
                     ]   
                 ]
])
                 
                 

In [11]:
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [12]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [13]:
arr = np.array([10,20,30,40,50])
mean_val = np.mean(arr)
std_dev = np.std(arr)
max_val = np.max(arr)
min_val = np.min(arr)
print("Array:", arr)
print("Mean:",mean_val)
print(f"Standard Deviation: {std_dev:.2f}")
print("Maximun:", max_val)
print("Minimum:", min_val)

Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.14
Maximun: 50
Minimum: 10


In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication (A x B):\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication (A x B):
 [[19 22]
 [43 50]]


In [15]:
print(array1.ndim)

1


In [16]:
print(A.ndim)

2


In [17]:
array6=np.array([1,2,3,4,5], ndmin=2)

In [18]:
print(array6.ndim)

2


In [19]:
array6.shape

(1, 5)

In [20]:
arrex=np.array([1,2,3,4,5])
arrex

array([1, 2, 3, 4, 5])

In [21]:
arrex.shape

(5,)

In [22]:
print(A[0][1])

2


In [23]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])

In [24]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [25]:
ch_arr2=np.array(["Supervised","unSupervised","sEMi-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [26]:
array_attributes=np.array([[10,20,30],[40,50,60]])

In [27]:
array_attributes.ndim

2

In [28]:
array_attributes.shape

(2, 3)

In [29]:
array_attributes.size

6

In [30]:
array_attributes.dtype

dtype('int32')

In [31]:
array_attributes.itemsize

4

In [32]:
array_attributes.data

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [41]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.random.random((2,2))

array([[0.94119886, 0.88733776],
       [0.09050861, 0.18570378]])

In [49]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [50]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [51]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
a = np.arange(5)

In [53]:
a

array([0, 1, 2, 3, 4])

In [54]:
a[2]

2

In [58]:
a[2:4]

array([2, 3])

In [59]:
a[:4:2] = -999

In [60]:
a

array([-999,    1, -999,    3,    4])

In [62]:
a[::-1]

array([   4,    3, -999,    1, -999])

In [63]:
for each_element in a:
    print(each_element)

-999
1
-999
3
4


In [78]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])

In [79]:
a[1,3]

8

In [80]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [81]:
lower_axes = a[1, :]

In [82]:
lower_axes

array([5, 6, 7, 8])

In [83]:
lower_axes.ndim

1

In [84]:
same_axes = a[1:2, :]

In [85]:
same_axes

array([[5, 6, 7, 8]])

In [86]:
a[:,1]

array([ 2,  6, 10])

In [87]:
a[:,1:2]

array([[ 2],
       [ 6],
       [10]])

In [88]:
for row in a:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [89]:
for each_element in a.flat:
    print(each_element)

1
2
3
4
5
6
7
8
9
10
11
12
