In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.2'

array1=np.array([1,2,3])

In [4]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [5]:
array2=np.array([[1,2],
               [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [6]:
array3d=np.array([[
                  [1,2],
                  [3,4]
                 ],
                 [
                 [5,6],
                 [7,8]
                 ]
                 ])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
array3d.shape


(2, 2, 2)

In [8]:
array3ex=np.array([
                  [
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ],
                  [
                   [10,11,12],
                   [13,14,15],
                   [16,17,18]   
                  ]
])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
array3ex.shape

(2, 3, 3)

In [10]:
array4d=np.array([
                 [
                  [
                   [1,2],
                   [3,4],
                   [5,6]   
                  ],
                    [
                     [7,8],
                     [9,10],
                     [11,12]   
                    ],
                     [
                      [13,14],
                      [15,16],
                      [17,18]   
                     ]   
                 ],
                 
                 [
                  [
                   [19,20],
                   [21,22],
                   [23,24]   
                  ],
                    [
                     [25,26],
                     [27,28],
                     [29,30]   
                    ],
                     [
                      [31,32],
                      [33,34],
                      [35,36]   
                     ]   
                 ]
])
                 
                 

In [11]:
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [12]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [16]:
arr = np.array([10,20,30,40,50])
mean_val = np.mean(arr)
std_dev = np.std(arr)
max_val = np.max(arr)
min_val = np.min(arr)
print("Array:", arr)
print("Mean:",mean_val)
print(f"Standard Deviation: {std_dev:.2f}")
print("Maximun:", max_val)
print("Minimum:", min_val)

Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.14
Maximun: 50
Minimum: 10


In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication (A x B):\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication (A x B):
 [[19 22]
 [43 50]]


In [25]:
print(array1.ndim)

1


In [26]:
print(A.ndim)

2


In [23]:
array6=np.array([1,2,3,4,5], ndmin=2)

In [27]:
print(array6.ndim)

2


In [28]:
array6.shape

(1, 5)

In [29]:
arrex=np.array([1,2,3,4,5])
arrex

array([1, 2, 3, 4, 5])

In [30]:
arrex.shape

(5,)

In [31]:
print(A[0][1])

2


In [34]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])

In [37]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [38]:
ch_arr2=np.array(["Supervised","unSupervised","sEMi-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')